# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: First Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build
          echo test, and deploy your project
          node -v
          npm -v
  build2:
     needs: build
     runs-on: ubuntu-latest
     steps:
      
      - name: Run a one-line script2
        run: ls -la

