name: First Workflow
on: [push]



runs:
    using: "composite"
    steps:
      - id: random-number-generator
        run: echo "random-id=$(echo $RANDOM)" >> $GITHUB_OUTPUT
        shell: bash


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build
        echo test, and deploy your project
        node -v
        npm -v