# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: self Workflow
on:
  push:
    paths:
      - "./src/**.ts"
      - "package.json"
      - "tsconfig.json"

jobs:
  # build:
  #   runs-on: self-hosted

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run a self-line script
  #       run: echo Hello, world!
  #     - name: Run self a multi-line script
  #       run: |
  #         echo Add other actions to build
  #         echo test, and deploy your project
  #         node -v
  #         npm -v

  # display-wd-info:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Display Working Directory & List Files
  #       run: |
  #         pwd
  #         ls -a
  #         echo $GITHUB_SHA
  #         echo $GITHUB_REPOSITORY
  #         echo $GITHUB_WORKSPACE
  #     - name: Change Working Dir
  #       working-directory: /home/runner
  #       run: pwd
  #     - name: Python Shell
  #       shell: python
  #       run: |
  #         import platform
  #         print(platform.processor())

  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  node:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: |
          echo JIRA_HOST=${{ secrets.JIRA_HOST }} >> .env
          echo JIRA_BEARER=${{ secrets.JIRA_BEARER }} >> .env

      - run: npm run build
      - run: |
          npm run pm2-start &
          sleep 10 &&
          curl http://localhost:8080
      # - name: Use Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      # - name: Install dependencies
      #   run: npm ci

      # - name: Run script
      #   run: node ./path/to/your/script.js
