# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: self Workflow
on:
  push:
    paths:
      - "./src/**.ts"
      - "package.json"
      - "tsconfig.json"
      - "./.github/workflows/self-workflow.yaml"
  workflow_dispatch:

jobs:
  node:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - run: |
          echo JIRA_HOST=${{ secrets.JIRA_HOST }} >> .env
          echo JIRA_EMAIL=${{ secrets.JIRA_EMAIL }} >> .env
          echo JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo SALT_ROUNDS=${{ secrets.SALT_ROUNDS }} >> .env
          echo DB_TYPE=${{ secrets.DB_TYPE }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo MIKRUS_KEY=${{ secrets.MIKRUS_KEY }} >> .env
          echo MIKRUS_SRV=${{ secrets.MIKRUS_SRV }} >> .env
          echo MIKRUS_HOST=${{ secrets.MIKRUS_HOST }} >> .env
          echo N8N_HOST=${{ secrets.N8N_HOST }} >> .env
          echo N8N_WEBHOOK_CALENDAR=${{ secrets.N8N_WEBHOOK_CALENDAR }} >> .env

      - run: npm run build
      - run: |
          npm run pm2-start 
          # &
          # sleep 20 &&
          # curl http://localhost:8080
